route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
    - smarthost: 'smtp.gmail.com:587'
      auth_username: 'rajasekharb974@gmail.com'
      auth_password: 'ogitmhesuvbnvjts'
      from: 'rajasekharb974@gmail.com'
      to: 'rajasekharb974@gmail.com'
      headers:
          subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']